// The Consolidation — curated dataset of US telecom M&A, 1983–2026.
// Values are announced transaction values in nominal $B (incl. assumed debt where
// that was the headline figure); null = undisclosed / stock swap / not meaningful.
// Sources: SEC filings, FCC orders, company press releases, contemporary coverage.

export const SECTORS = {
  fiber:     { name: 'Fiber & Infrastructure', ui: '#199e70', glow: '#2dd694', angle: 0,   spread: 58 },
  wireline:  { name: 'Wireline / Bell System', ui: '#c98500', glow: '#ffb833', angle: 72,  spread: 66 },
  cable:     { name: 'Cable',                  ui: '#d55181', glow: '#ff7aa8', angle: 144, spread: 52 },
  wireless:  { name: 'Wireless',               ui: '#3987e5', glow: '#62a8ff', angle: 216, spread: 60 },
  satellite: { name: 'Satellite',              ui: '#d95926', glow: '#ff8a52', angle: 288, spread: 44 },
};

export const FAILED_COLOR = '#d03b3b';   // reserved status red — failed / blocked deals
export const PENDING_COLOR = '#c3c2b7';  // neutral — announced, not yet closed

export const START_YEAR = 1983;
export const END_YEAR = 2026.6; // "present" edge of the scene

// ---------------------------------------------------------------------------
// Companies. born: year the thread appears (1983 = "existed before our window").
// spawnedFrom: thread forks off another company (spinoff / breakup child).
// renames: label changes along the thread. weight: relative visual thickness seed.
// ---------------------------------------------------------------------------
export const COMPANIES = [
  // ---- Wireline / Bell ----
  { id: 'bellsystem', name: 'The Bell System', sector: 'wireline', born: 1983, weight: 6,
    note: 'AT&T and its Bell Operating Companies — a regulated monopoly serving >80% of US phones.' },
  { id: 'attcorp', name: 'AT&T Corp.', sector: 'wireline', born: 1984, spawnedFrom: 'bellsystem', weight: 3,
    note: 'The long-distance and equipment rump of the old monopoly.' },
  { id: 'ameritech', name: 'Ameritech', sector: 'wireline', born: 1984, spawnedFrom: 'bellsystem', weight: 2 },
  { id: 'bellatlantic', name: 'Bell Atlantic', sector: 'wireline', born: 1984, spawnedFrom: 'bellsystem', weight: 2,
    renames: [{ year: 2000.5, name: 'Verizon' }] },
  { id: 'bellsouth', name: 'BellSouth', sector: 'wireline', born: 1984, spawnedFrom: 'bellsystem', weight: 2 },
  { id: 'nynex', name: 'NYNEX', sector: 'wireline', born: 1984, spawnedFrom: 'bellsystem', weight: 2 },
  { id: 'pactel', name: 'Pacific Telesis', sector: 'wireline', born: 1984, spawnedFrom: 'bellsystem', weight: 2 },
  { id: 'sbc', name: 'Southwestern Bell', sector: 'wireline', born: 1984, spawnedFrom: 'bellsystem', weight: 2,
    renames: [{ year: 1995, name: 'SBC' }, { year: 2005.9, name: 'AT&T Inc.' }] },
  { id: 'uswest', name: 'US West', sector: 'wireline', born: 1984, spawnedFrom: 'bellsystem', weight: 2 },
  { id: 'gte', name: 'GTE', sector: 'wireline', born: 1983, weight: 2.5,
    note: 'The biggest non-Bell phone company — the "independent" giant.' },
  { id: 'contel', name: 'Contel', sector: 'wireline', born: 1983, weight: 1 },
  { id: 'snet', name: 'SNET', sector: 'wireline', born: 1983, weight: 1,
    note: 'Southern New England Telephone — Connecticut’s independent Bell.' },
  { id: 'mci', name: 'MCI', sector: 'wireline', born: 1983, weight: 2,
    note: 'The upstart that sued the Bell System open.' },
  { id: 'worldcom', name: 'WorldCom (LDDS)', sector: 'wireline', born: 1983, weight: 2,
    renames: [{ year: 2003.3, name: 'MCI (post-fraud)' }],
    note: 'A Mississippi long-distance reseller that ate 60+ companies in 15 years.' },
  { id: 'centurytel', name: 'Century Telephone', sector: 'wireline', born: 1983, weight: 1.5,
    renames: [{ year: 2009.5, name: 'CenturyLink' }, { year: 2020.7, name: 'Lumen' }] },
  { id: 'embarq', name: 'Embarq', sector: 'wireline', born: 2006.4, spawnedFrom: 'sprint', weight: 1.5,
    note: 'Sprint’s local phone business, spun off in 2006.' },
  { id: 'citizens', name: 'Citizens Utilities', sector: 'wireline', born: 1983, weight: 1.5,
    renames: [{ year: 2001.5, name: 'Frontier' }] },
  { id: 'frontiercorp', name: 'Frontier Corp. (Rochester Tel)', sector: 'wireline', born: 1983, weight: 1 },
  { id: 'windstream', name: 'Windstream', sector: 'wireline', born: 2006.5, spawnedFrom: 'alltel', weight: 1.5,
    note: 'Alltel’s wireline business merged with Valor Communications. Ch. 11 in 2019, emerged 2021.' },
  { id: 'brightspeed', name: 'Brightspeed', sector: 'wireline', born: 2022.75, spawnedFrom: 'centurytel', weight: 1,
    note: 'Lumen’s copper-heavy ILEC territories in 20 states, carved out to Apollo for $7.5B.' },
  { id: 'ziply', name: 'Ziply Fiber', sector: 'wireline', born: 2020.3, spawnedFrom: 'citizens', weight: 1,
    note: 'Frontier’s Pacific Northwest operations, carved out for $1.35B by a Searchlight-led group.' },

  // ---- Wireless ----
  { id: 'sprint', name: 'Sprint (United Telecom)', sector: 'wireless', born: 1983, weight: 2.5,
    note: 'Long-distance fiber pioneer turned #3 wireless carrier.' },
  { id: 'nextel', name: 'Nextel', sector: 'wireless', born: 1987, weight: 1.5,
    note: 'Built a national network out of taxi-dispatch radio spectrum.' },
  { id: 'mccaw', name: 'McCaw Cellular', sector: 'wireless', born: 1983, weight: 1.5,
    note: 'The first national cellular carrier, assembled license by license.' },
  { id: 'airtouch', name: 'AirTouch', sector: 'wireless', born: 1994.2, spawnedFrom: 'pactel', weight: 1.5,
    note: 'Pacific Telesis’s cellular arm, spun off in 1994.' },
  { id: 'attwireless', name: 'AT&T Wireless', sector: 'wireless', born: 2001.5, spawnedFrom: 'attcorp', weight: 2,
    note: 'Spun out of AT&T in 2001 — its IPO was the largest in US history at the time.' },
  { id: 'cingular', name: 'Cingular', sector: 'wireless', born: 2000.75, spawnedFrom: 'sbc', weight: 2,
    note: 'A 60/40 joint venture of SBC and BellSouth’s wireless operations.' },
  { id: 'voicestream', name: 'VoiceStream', sector: 'wireless', born: 1994, weight: 1.5,
    renames: [{ year: 2002.5, name: 'T-Mobile US' }] },
  { id: 'metropcs', name: 'MetroPCS', sector: 'wireless', born: 1994, weight: 1 },
  { id: 'clearwire', name: 'Clearwire', sector: 'wireless', born: 2003, weight: 1 },
  { id: 'alltel', name: 'Alltel', sector: 'wireless', born: 1983, weight: 1.5 },
  { id: 'uscellular', name: 'UScellular', sector: 'wireless', born: 1983, weight: 1.2,
    renames: [{ year: 2025.7, name: 'Array Digital Infrastructure' }] },
  { id: 'tracfone', name: 'TracFone', sector: 'wireless', born: 1996, weight: 1 },
  { id: 'leap', name: 'Leap (Cricket)', sector: 'wireless', born: 1998.5, weight: 1 },
  { id: 'mint', name: 'Mint Mobile', sector: 'wireless', born: 2016.5, weight: 0.8 },

  // ---- Cable ----
  { id: 'comcast', name: 'Comcast', sector: 'cable', born: 1983, weight: 2.5 },
  { id: 'tci', name: 'TCI', sector: 'cable', born: 1983, weight: 2,
    note: 'Tele-Communications Inc. — John Malone’s cable empire, the biggest operator of the ’80s.' },
  { id: 'twc', name: 'Time Warner Cable', sector: 'cable', born: 1992, weight: 2,
    note: 'Fully split from Time Warner in 2009.' },
  { id: 'charter', name: 'Charter', sector: 'cable', born: 1993, weight: 2,
    note: 'Paul Allen’s roll-up vehicle. Ch. 11 in 2009, then the industry’s biggest consolidator.' },
  { id: 'cox', name: 'Cox', sector: 'cable', born: 1983, weight: 1.8,
    note: 'Family-owned since 1962 — the great holdout.' },
  { id: 'cablevision', name: 'Cablevision', sector: 'cable', born: 1983, weight: 1.5 },
  { id: 'adelphia', name: 'Adelphia', sector: 'cable', born: 1983, weight: 1.5,
    note: 'Collapsed in a 2002 accounting fraud; sold out of bankruptcy.' },
  { id: 'suddenlink', name: 'Suddenlink', sector: 'cable', born: 2003, weight: 1 },
  { id: 'brighthouse', name: 'Bright House', sector: 'cable', born: 2003, weight: 1 },
  { id: 'mediaone', name: 'MediaOne', sector: 'cable', born: 1996.5, spawnedFrom: 'uswest', weight: 1.5,
    note: 'US West’s cable arm (built on Continental Cablevision), split off in 1998.' },
  { id: 'attbroadband', name: 'AT&T Broadband', sector: 'cable', born: 2001.2, spawnedFrom: 'attcorp', weight: 2,
    note: 'The cable empire AT&T bought for ~$100B, spun off after the strategy failed.' },
  { id: 'altice', name: 'Altice USA', sector: 'cable', born: 2015.4, weight: 1.5,
    note: 'Patrick Drahi’s US beachhead.' },
  { id: 'libertybb', name: 'Liberty Broadband', sector: 'cable', born: 2014.8, weight: 1,
    note: 'John Malone’s holding vehicle for his Charter stake.' },

  // ---- Satellite ----
  { id: 'directv', name: 'DirecTV', sector: 'satellite', born: 1994.4, weight: 1.8,
    note: 'Hughes Electronics’ satellite-TV moonshot.' },
  { id: 'echostar', name: 'EchoStar', sector: 'satellite', born: 1983, weight: 1.8,
    note: 'Charlie Ergen’s empire — launched the Dish network in 1996.' },
  { id: 'dish', name: 'DISH Network', sector: 'satellite', born: 2008, spawnedFrom: 'echostar', weight: 1.5,
    note: 'Split from EchoStar in 2008; bet everything on becoming the 4th wireless carrier.' },
  { id: 'directv2', name: 'DirecTV (TPG era)', sector: 'satellite', born: 2021.6, spawnedFrom: 'sbc', weight: 1.2,
    note: 'Spun back out of AT&T at ~$16B — a third of what AT&T paid six years earlier.' },
  { id: 'starlink', name: 'Starlink (SpaceX)', sector: 'satellite', born: 2019, weight: 1.5,
    note: 'The new satellite incumbent — broadband from low Earth orbit.' },

  // ---- Fiber & Infrastructure ----
  { id: 'qwest', name: 'Qwest', sector: 'fiber', born: 1996.2, weight: 2,
    note: 'Laid fiber along Southern Pacific rail rights-of-way during the bubble.' },
  { id: 'level3', name: 'Level 3', sector: 'fiber', born: 1998, weight: 2 },
  { id: 'globalcrossing', name: 'Global Crossing', sector: 'fiber', born: 1997.2, weight: 1.5,
    note: 'Undersea-fiber highflier. Ch. 11 in 2002 — $47B of market value erased.' },
  { id: 'twtelecom', name: 'TW Telecom', sector: 'fiber', born: 1998.5, weight: 1 },
  { id: 'zayo', name: 'Zayo', sector: 'fiber', born: 2007.4, weight: 1.5,
    note: 'A bandwidth roll-up built from 40+ acquisitions.' },
  { id: 'abovenet', name: 'AboveNet', sector: 'fiber', born: 1996, weight: 1 },
  { id: 'xo', name: 'XO Communications', sector: 'fiber', born: 1996, weight: 1 },
  { id: 'crowncastle', name: 'Crown Castle', sector: 'fiber', born: 1994.5, weight: 1.5,
    note: 'Tower REIT that spent $16B+ buying fiber — then sold it all back off.' },
  { id: 'lightower', name: 'Lightower', sector: 'fiber', born: 2006.5, weight: 1 },
  { id: 'cogent', name: 'Cogent', sector: 'fiber', born: 1999.5, weight: 1 },
  { id: 'metronet', name: 'Metronet', sector: 'fiber', born: 2005.5, weight: 1 },
  { id: 'lumos', name: 'Lumos', sector: 'fiber', born: 2015, weight: 0.8 },
  { id: 'uniti', name: 'Uniti', sector: 'fiber', born: 2015.3, spawnedFrom: 'windstream', weight: 1.2,
    note: 'Windstream’s network, spun into a REIT (as CS&L) in 2015.' },
];

// ---------------------------------------------------------------------------
// Deals. type: 'merge' (target thread ends into acquirer) | 'asset' (a tributary
// of the seller joins the acquirer; seller thread survives) | 'split' (parent
// shatters into its spawned children) | 'external' (buyer has no thread — node
// sits on the target thread, which continues) | 'failed' (announced, then
// blocked/abandoned) | 'pending' (announced, not closed as of mid-2026).
// Year = close (merge/asset), announcement (failed/pending/external where noted).
// ---------------------------------------------------------------------------
export const DEALS = [
  // ---- The Breakup ----
  { id: 'breakup', year: 1984, type: 'split', target: 'bellsystem', valueB: null,
    title: 'The Bell System breakup',
    note: 'The largest corporate breakup in history. A 1982 consent decree splits AT&T into a long-distance company and seven regional "Baby Bells" on January 1, 1984.' },

  // ---- 1984–1995 ----
  { id: 'gte-contel', year: 1991, type: 'merge', acquirer: 'gte', target: 'contel', valueB: 6.6,
    title: 'GTE acquires Contel', note: 'The independents consolidate first.' },
  { id: 'att-mccaw', year: 1994.7, type: 'merge', acquirer: 'attcorp', target: 'mccaw', valueB: 11.5,
    title: 'AT&T buys McCaw Cellular',
    note: 'AT&T buys its way back into the local business it was forced to leave — this time by radio.' },

  // ---- 1996–2000: the free-for-all ----
  { id: 'sbc-pactel', year: 1997.3, type: 'merge', acquirer: 'sbc', target: 'pactel', valueB: 16.7,
    title: 'SBC acquires Pacific Telesis', note: 'The first Baby Bell to swallow a sibling.' },
  { id: 'ba-nynex', year: 1997.6, type: 'merge', acquirer: 'bellatlantic', target: 'nynex', valueB: 25.6,
    title: 'Bell Atlantic merges with NYNEX', note: 'Two Bells become one along the entire East Coast.' },
  { id: 'sbc-snet', year: 1998.8, type: 'merge', acquirer: 'sbc', target: 'snet', valueB: 4.4,
    title: 'SBC acquires SNET' },
  { id: 'wcom-mci', year: 1998.7, type: 'merge', acquirer: 'worldcom', target: 'mci', valueB: 37,
    title: 'WorldCom wins MCI',
    note: 'A company one-fifth MCI’s size outbids British Telecom and GTE. The biggest merger in history at the time.' },
  { id: 'gc-frontier', year: 1999.7, type: 'merge', acquirer: 'globalcrossing', target: 'frontiercorp', valueB: 11.2,
    title: 'Global Crossing buys Frontier', note: 'Bubble-era fiber money buys a 100-year-old Rochester phone company.' },
  { id: 'sbc-ameritech', year: 1999.75, type: 'merge', acquirer: 'sbc', target: 'ameritech', valueB: 62,
    title: 'SBC acquires Ameritech', note: 'Two of the seven Baby Bells are now one company covering 13 states.' },
  { id: 'att-tci', year: 1999.2, type: 'merge', acquirer: 'attcorp', target: 'tci', valueB: 48,
    title: 'AT&T acquires TCI',
    note: 'AT&T bets the company on cable as its route back into local access.' },
  { id: 'vod-airtouch', year: 1999.5, type: 'external', target: 'airtouch', valueB: 60,
    buyer: 'Vodafone', title: 'Vodafone acquires AirTouch',
    note: 'The UK giant outbids Bell Atlantic for America’s largest independent cellular carrier.' },
  { id: 'wcom-sprint', year: 2000.5, type: 'failed', acquirer: 'worldcom', target: 'sprint', valueB: 129,
    title: 'WorldCom–Sprint: blocked',
    note: 'The largest merger ever proposed — $129B — killed by US and EU regulators in 2000. WorldCom’s growth story dies with it; the fraud surfaces two years later.' },
  { id: 'qwest-uswest', year: 2000.5, type: 'merge', acquirer: 'qwest', target: 'uswest', valueB: 35,
    title: 'Qwest swallows US West',
    note: 'A four-year-old fiber startup wins a bidding war for a Baby Bell 10× its size.' },
  { id: 'ba-gte', year: 2000.5, type: 'merge', acquirer: 'bellatlantic', target: 'gte', valueB: 52.8,
    rename: 'Verizon', title: 'Bell Atlantic + GTE = Verizon',
    note: 'The combined company takes a new name: veritas + horizon.' },
  { id: 'att-mediaone', year: 2000.4, type: 'merge', acquirer: 'attcorp', target: 'mediaone', valueB: 44,
    title: 'AT&T acquires MediaOne',
    note: 'AT&T tops Comcast’s bid, briefly becoming America’s biggest cable operator — for ~$100B all-in.' },
  { id: 'vzw-jv', year: 2000.3, type: 'merge', acquirer: 'bellatlantic', target: 'airtouch', valueB: null,
    title: 'Verizon Wireless is born',
    note: 'Bell Atlantic and Vodafone pool their US wireless assets into a 55/45 joint venture.' },

  // ---- 2001–2006: the re-assembly ----
  { id: 'dt-voicestream', year: 2001.4, type: 'external', target: 'voicestream', valueB: 35,
    buyer: 'Deutsche Telekom', title: 'Deutsche Telekom buys VoiceStream',
    note: 'Rebranded T-Mobile USA in 2002. Announced at $50B+ in stock at the bubble’s peak; worth ~$35B by close.' },
  { id: 'echostar-directv', year: 2002.8, type: 'failed', acquirer: 'echostar', target: 'directv', valueB: 26,
    title: 'EchoStar–DirecTV: blocked',
    note: 'The FCC and DOJ refuse to let satellite TV become a monopoly. Ergen will try again for two decades.' },
  { id: 'newscorp-hughes', year: 2003.9, type: 'external', target: 'directv', valueB: 6.6,
    buyer: 'News Corp', title: 'News Corp takes control of DirecTV' },
  { id: 'comcast-attbb', year: 2002.85, type: 'merge', acquirer: 'comcast', target: 'attbroadband', valueB: 72,
    title: 'Comcast acquires AT&T Broadband',
    note: 'AT&T’s $100B cable adventure ends. Comcast becomes the biggest cable company in America — and stays there.' },
  { id: 'cingular-attw', year: 2004.8, type: 'merge', acquirer: 'cingular', target: 'attwireless', valueB: 41,
    title: 'Cingular buys AT&T Wireless',
    note: 'The largest all-cash deal in history at the time.' },
  { id: 'sprint-nextel', year: 2005.6, type: 'merge', acquirer: 'sprint', target: 'nextel', valueB: 35,
    title: 'Sprint merges with Nextel',
    note: 'A "merger of equals" that becomes a case study in integration failure. Most of the value is written off by 2008.' },
  { id: 'sbc-att', year: 2005.9, type: 'merge', acquirer: 'sbc', target: 'attcorp', valueB: 16,
    rename: 'AT&T Inc.', title: 'SBC acquires AT&T',
    note: 'The child buys the parent — for less than SBC paid for Pacific Telesis — and takes its name.' },
  { id: 'vz-mci', year: 2006.0, type: 'merge', acquirer: 'bellatlantic', target: 'worldcom', valueB: 8.5,
    title: 'Verizon acquires MCI',
    note: 'After a bidding war with Qwest, the wreckage of WorldCom goes to Verizon.' },
  { id: 'comcast-adelphia', year: 2006.55, type: 'merge', acquirer: 'comcast', target: 'adelphia', valueB: 17.6,
    title: 'Comcast & TWC carve up Adelphia',
    note: 'The #5 cable company, sold out of fraud-driven bankruptcy and split between its two biggest rivals.' },
  { id: 'att-bellsouth', year: 2006.95, type: 'merge', acquirer: 'sbc', target: 'bellsouth', valueB: 86,
    title: 'AT&T acquires BellSouth',
    note: 'Four of the seven Baby Bells are now back under one roof — and Ma Bell’s name is back on the door.' },
  { id: 'cingular-fold', year: 2007.0, type: 'merge', acquirer: 'sbc', target: 'cingular', valueB: null,
    title: 'Cingular becomes AT&T Mobility',
    note: 'The BellSouth deal gives AT&T 100% of Cingular; the brand is retired.' },

  // ---- 2007–2014: wireless wars ----
  { id: 'alltel-lbo', year: 2007.9, type: 'external', target: 'alltel', valueB: 27.5,
    buyer: 'TPG & Goldman Sachs', title: 'Alltel goes private',
    note: 'The biggest private-equity telecom buyout ever — 18 months before the assets are flipped to Verizon.' },
  { id: 'vz-alltel', year: 2009.0, type: 'merge', acquirer: 'bellatlantic', target: 'alltel', valueB: 28.1,
    title: 'Verizon acquires Alltel', note: 'Verizon Wireless becomes America’s largest carrier.' },
  { id: 'ctl-embarq', year: 2009.5, type: 'merge', acquirer: 'centurytel', target: 'embarq', valueB: 11.6,
    rename: 'CenturyLink', title: 'CenturyTel + Embarq = CenturyLink' },
  { id: 'frontier-vz10', year: 2010.5, type: 'asset', acquirer: 'citizens', target: 'bellatlantic', valueB: 8.6,
    title: 'Frontier buys Verizon’s rural lines',
    note: '4.8M rural access lines in 14 states — tripling Frontier’s size.' },
  { id: 'ctl-qwest', year: 2011.25, type: 'merge', acquirer: 'centurytel', target: 'qwest', valueB: 22.4,
    title: 'CenturyLink acquires Qwest',
    note: 'A rural Louisiana phone company ends up owning a Baby Bell.' },
  { id: 'l3-gc', year: 2011.75, type: 'merge', acquirer: 'level3', target: 'globalcrossing', valueB: 3,
    title: 'Level 3 acquires Global Crossing',
    note: 'Two survivors of the fiber bubble combine — for 6% of Global Crossing’s peak value.' },
  { id: 'att-tmo-fail', year: 2011.9, type: 'failed', acquirer: 'sbc', target: 'voicestream', valueB: 39,
    title: 'AT&T–T-Mobile: abandoned',
    note: 'DOJ sues; AT&T walks away and pays a $4B+ breakup package that funds T-Mobile’s comeback.' },
  { id: 'zayo-abovenet', year: 2012.5, type: 'merge', acquirer: 'zayo', target: 'abovenet', valueB: 2.2,
    title: 'Zayo acquires AboveNet' },
  { id: 'tmo-metropcs', year: 2013.3, type: 'merge', acquirer: 'voicestream', target: 'metropcs', valueB: 1.5,
    title: 'T-Mobile merges with MetroPCS',
    note: 'A reverse merger takes T-Mobile public — and gives it a prepaid engine.' },
  { id: 'softbank-sprint', year: 2013.5, type: 'external', target: 'sprint', valueB: 21.6,
    buyer: 'SoftBank', title: 'SoftBank takes control of Sprint' },
  { id: 'sprint-clearwire', year: 2013.5, type: 'merge', acquirer: 'sprint', target: 'clearwire', valueB: 3.5,
    title: 'Sprint buys out Clearwire',
    note: 'Full control of the 2.5 GHz trove that later becomes T-Mobile’s 5G crown jewel.' },
  { id: 'vz-vodafone', year: 2014.1, type: 'external', target: 'bellatlantic', valueB: 130,
    buyer: '(buyout of Vodafone’s stake)', title: 'Verizon buys out Vodafone',
    note: '$130B for the 45% of Verizon Wireless it didn’t own — the third-largest corporate deal ever signed.' },
  { id: 'att-leap', year: 2014.2, type: 'merge', acquirer: 'sbc', target: 'leap', valueB: 1.2,
    title: 'AT&T acquires Leap (Cricket)' },
  { id: 'frontier-attct', year: 2014.8, type: 'asset', acquirer: 'citizens', target: 'sbc', valueB: 2,
    title: 'Frontier buys AT&T’s Connecticut lines',
    note: 'SNET changes hands again.' },
  { id: 'l3-twtelecom', year: 2014.85, type: 'merge', acquirer: 'level3', target: 'twtelecom', valueB: 7.3,
    title: 'Level 3 acquires TW Telecom' },

  // ---- 2015–2019: cable consolidates ----
  { id: 'comcast-twc-fail', year: 2015.3, type: 'failed', acquirer: 'comcast', target: 'twc', valueB: 45.2,
    title: 'Comcast–TWC: abandoned',
    note: 'Regulators balk at one company controlling over half of US broadband. Comcast walks.' },
  { id: 'att-directv', year: 2015.55, type: 'merge', acquirer: 'sbc', target: 'directv', valueB: 48.5,
    title: 'AT&T acquires DirecTV',
    note: '$48.5B ($67B with debt) for satellite TV at its subscriber peak — the top of the market, precisely.' },
  { id: 'altice-suddenlink', year: 2015.95, type: 'merge', acquirer: 'altice', target: 'suddenlink', valueB: 9.1,
    title: 'Altice acquires Suddenlink', note: 'Drahi’s first US move.' },
  { id: 'charter-twc', year: 2016.4, type: 'merge', acquirer: 'charter', target: 'twc', valueB: 78.7,
    title: 'Charter acquires Time Warner Cable',
    note: 'Backed by John Malone, Charter leaps from #4 to #2 in one deal.' },
  { id: 'charter-bh', year: 2016.42, type: 'merge', acquirer: 'charter', target: 'brighthouse', valueB: 10.4,
    title: 'Charter acquires Bright House' },
  { id: 'altice-cablevision', year: 2016.5, type: 'merge', acquirer: 'altice', target: 'cablevision', valueB: 17.7,
    title: 'Altice acquires Cablevision', note: 'The Dolan family sells after 43 years.' },
  { id: 'frontier-ctf', year: 2016.3, type: 'asset', acquirer: 'citizens', target: 'bellatlantic', valueB: 10.5,
    title: 'Frontier buys Verizon’s CA/TX/FL systems',
    note: 'The deal that breaks Frontier — Ch. 11 follows in 2020.' },
  { id: 'vz-xo', year: 2017.1, type: 'merge', acquirer: 'bellatlantic', target: 'xo', valueB: 1.8,
    title: 'Verizon acquires XO' },
  { id: 'ctl-l3', year: 2017.85, type: 'merge', acquirer: 'centurytel', target: 'level3', valueB: 34,
    title: 'CenturyLink acquires Level 3',
    note: 'The last of the great fiber-bubble networks folds into the old phone system.' },
  { id: 'cc-lightower', year: 2017.85, type: 'merge', acquirer: 'crowncastle', target: 'lightower', valueB: 7.1,
    title: 'Crown Castle acquires Lightower', note: 'The peak of the tower industry’s fiber landgrab.' },

  // ---- 2020–2026: endgame ----
  { id: 'tmo-sprint', year: 2020.25, type: 'merge', acquirer: 'voicestream', target: 'sprint', valueB: 26.5,
    title: 'T-Mobile merges with Sprint',
    note: 'Four national carriers become three. The un-carrier becomes an incumbent.' },
  { id: 'dish-boost', year: 2020.5, type: 'asset', acquirer: 'dish', target: 'voicestream', valueB: 1.4,
    title: 'DISH buys Boost',
    note: 'The DOJ’s remedy: hand DISH the parts to build a 4th carrier. It never really happens.' },
  { id: 'zayo-lbo', year: 2020.2, type: 'external', target: 'zayo', valueB: 14.3,
    buyer: 'EQT & DigitalBridge', title: 'Zayo goes private' },
  { id: 'lumen-rename', year: 2020.7, type: 'external', target: 'centurytel', valueB: null,
    buyer: null, title: 'CenturyLink becomes Lumen', hideNode: true,
    note: 'A rebrand for the fiber-and-edge era.' },
  { id: 'vz-tracfone', year: 2021.9, type: 'merge', acquirer: 'bellatlantic', target: 'tracfone', valueB: 6.9,
    title: 'Verizon acquires TracFone', note: '20M prepaid subscribers move in-house.' },
  { id: 'att-directv-spin', year: 2021.6, type: 'split', target: null, spawn: 'directv2', valueB: 16.25,
    title: 'AT&T spins off DirecTV',
    note: 'TPG buys 30% at a ~$16B valuation. AT&T paid $67B with debt in 2015.' },
  { id: 'lumen-brightspeed', year: 2022.75, type: 'asset', acquirer: 'brightspeed', target: 'centurytel', valueB: 7.5,
    title: 'Lumen sheds 20 states to Apollo',
    note: 'The copper heartland becomes Brightspeed.' },
  { id: 'cogent-sprintwl', year: 2023.35, type: 'asset', acquirer: 'cogent', target: 'voicestream', valueB: null,
    title: 'Cogent buys Sprint’s wireline network',
    note: 'Purchase price: one dollar. T-Mobile pays Cogent $700M to take it away.' },
  { id: 'echostar-dish', year: 2023.95, type: 'merge', acquirer: 'echostar', target: 'dish', valueB: null,
    title: 'EchoStar and DISH reunite',
    note: 'Fifteen years after the split, Ergen recombines them — mostly to shuffle debt.' },
  { id: 'tmo-mint', year: 2024.4, type: 'merge', acquirer: 'voicestream', target: 'mint', valueB: 1.35,
    title: 'T-Mobile acquires Mint Mobile',
    note: 'Ryan Reynolds’ MVNO sells for $1.35B.' },
  { id: 'directv-dish-fail', year: 2024.9, type: 'failed', acquirer: 'directv2', target: 'echostar', valueB: null,
    title: 'DirecTV–DISH: collapsed',
    note: 'Price: $1, plus $9.8B of debt. DISH’s bondholders refuse the haircut and kill the deal in weeks.' },
  { id: 'tmo-lumos', year: 2025.25, type: 'merge', acquirer: 'voicestream', target: 'lumos', valueB: 0.95,
    title: 'T-Mobile & EQT acquire Lumos', jv: true,
    note: 'The un-carrier’s first fiber JV.' },
  { id: 'tmo-metronet', year: 2025.55, type: 'merge', acquirer: 'voicestream', target: 'metronet', valueB: 4.9,
    title: 'T-Mobile & KKR acquire Metronet', jv: true,
    note: '713K fiber customers; carriers now want the wires too.' },
  { id: 'tmo-uscc', year: 2025.6, type: 'merge', acquirer: 'voicestream', target: 'uscellular', valueB: 4.4,
    title: 'T-Mobile absorbs UScellular',
    note: 'The last big regional carrier sells its wireless business; the remainder becomes Array Digital Infrastructure.' },
  { id: 'uniti-windstream', year: 2025.6, type: 'merge', acquirer: 'uniti', target: 'windstream', valueB: 13.4,
    title: 'Uniti and Windstream reunite',
    note: 'The REIT re-merges with the tenant it was spun out of a decade earlier.' },
  { id: 'bce-ziply', year: 2025.6, type: 'external', target: 'ziply', valueB: 3.6,
    buyer: 'BCE (Bell Canada)', title: 'Bell Canada acquires Ziply',
    note: 'Canada’s Bell buys into US fiber — $3.6B cash plus assumed debt.' },
  { id: 'cc-fibersale', year: 2025.2, type: 'asset', acquirer: 'zayo', target: 'crowncastle', valueB: 8.5,
    title: 'Crown Castle sells its fiber unit',
    note: 'Zayo takes the fiber, EQT the small cells — $8.5B combined. The tower fiber experiment ends.' },
  { id: 'echostar-att-spectrum', year: 2025.65, type: 'asset', acquirer: 'sbc', target: 'echostar', valueB: 23,
    title: 'AT&T buys EchoStar’s spectrum',
    note: '50 MHz of nationwide licenses for ~$23B. The 4th-carrier dream is liquidated.' },
  { id: 'echostar-spacex-spectrum', year: 2025.7, type: 'asset', acquirer: 'starlink', target: 'echostar', valueB: 17,
    title: 'SpaceX buys EchoStar’s AWS-4 & H-block',
    note: '$17B in cash and SpaceX stock — spectrum for a direct-to-cell Starlink constellation.' },
  { id: 'tpg-directv', year: 2025.55, type: 'external', target: 'directv2', valueB: 7.6,
    buyer: 'TPG', title: 'TPG buys out AT&T’s DirecTV stake' },
  { id: 'vz-frontier', year: 2026.05, type: 'merge', acquirer: 'bellatlantic', target: 'citizens', valueB: 20,
    title: 'Verizon acquires Frontier',
    note: 'Verizon buys back — for $20B — much of the network it sold Frontier a decade earlier.' },
  { id: 'att-lumen-fiber', year: 2026.1, type: 'asset', acquirer: 'sbc', target: 'centurytel', valueB: 5.75,
    title: 'AT&T buys Lumen’s consumer fiber',
    note: '1M fiber subscribers across 11 states. Closed February 2, 2026.' },
  { id: 'charter-cox', year: 2026.45, type: 'pending', acquirer: 'charter', target: 'cox', valueB: 34.5,
    title: 'Charter + Cox (pending)',
    note: 'Announced May 2025; FCC approved February 2026; awaiting California. The combined company will take the Cox name — the last great cable holdout finally deals.' },
  { id: 'charter-libertybb', year: 2026.55, type: 'pending', acquirer: 'charter', target: 'libertybb', valueB: null,
    title: 'Charter + Liberty Broadband (pending)',
    note: 'Malone’s holding company folds in — expected 2027, closing the 50-year arc of cable’s great dealmaker.' },
];

// ---------------------------------------------------------------------------
// Chapters — scroll narrative. yearFrom/yearTo drive the camera; text is DOM.
// ---------------------------------------------------------------------------
export const CHAPTERS = [
  { id: 'prologue', yearFrom: 1983.0, yearTo: 1983.9, kicker: '1983', title: 'One company owned American telephony.',
    body: 'The Bell System — AT&T and its operating companies — carried over 80% of the nation’s calls. It employed a million people. It had been a legal monopoly for most of a century. This is the story of what happened when it shattered — and how, over forty years and a trillion dollars of deals, the pieces put themselves back together.' },
  { id: 'breakup', yearFrom: 1984.0, yearTo: 1995.5, kicker: '1984', title: 'The Breakup.',
    body: 'On January 1, 1984, a federal consent decree splits AT&T into a long-distance carrier and seven regional "Baby Bells." It is the largest corporate breakup in history. For a decade the pieces drift apart — while outsiders like MCI, McCaw, and the cable operators grow in the open space.' },
  { id: 'freeforall', yearFrom: 1995.5, yearTo: 2000.9, kicker: '1996', title: 'The Free-for-All.',
    body: 'The Telecommunications Act of 1996 tears down the fences: anyone can now enter anyone’s market. The response is not competition — it is consolidation. Bells merge with Bells. WorldCom devours MCI. A four-year-old fiber startup swallows a Baby Bell. By 2000, the seven siblings are already four.' },
  { id: 'reassembly', yearFrom: 2000.9, yearTo: 2007.2, kicker: '2001–2006', title: 'The Re-assembly.',
    body: 'The bubble bursts. WorldCom collapses in the biggest fraud in American history; AT&T’s $100B cable adventure fails. In 2005 the unthinkable happens: SBC — once the smallest Baby Bell — buys its own former parent and takes its name. A year later it adds BellSouth. Ma Bell is back.' },
  { id: 'wireless', yearFrom: 2007.2, yearTo: 2014.9, kicker: '2007–2014', title: 'The Wireless Wars.',
    body: 'Voice minutes give way to data plans, and the deal flow follows the airwaves. Verizon swallows Alltel to become #1. Washington blocks AT&T from buying T-Mobile — then watches SoftBank buy Sprint. And Verizon signs the third-largest deal in corporate history just to own all of itself.' },
  { id: 'cable', yearFrom: 2014.9, yearTo: 2019.9, kicker: '2015–2019', title: 'Cable Consolidates.',
    body: 'Streaming panic sets in. Comcast’s bid for Time Warner Cable dies in Washington — so Charter takes it instead, tripling overnight. Altice buys its way in from Europe. AT&T pays $67B for DirecTV at satellite TV’s exact subscriber peak. It will not age well.' },
  { id: 'endgame', yearFrom: 2019.9, yearTo: 2026.6, kicker: '2020–2026', title: 'The Endgame.',
    body: 'Four carriers become three when T-Mobile absorbs Sprint. The losers liquidate: DISH’s 4th-carrier dream is sold off as spectrum, DirecTV changes hands for a dollar and debt, and the copper empires are carved up for their fiber. Even the holdouts fall — Cox, family-owned for 63 years, agrees to merge.' },
  { id: 'epilogue', yearFrom: 2026.6, yearTo: 2026.6, kicker: 'Today', title: 'Three trunks, forty years.',
    body: 'More than sixty companies flowed into a handful of survivors. The Bell System was broken up so competition could flourish — and competition’s answer was to rebuild it, three times over.' },
];

export const META = {
  title: 'The Consolidation',
  subtitle: 'Forty years of American telecom mergers, 1984–2026',
  dataNote: 'Deal values are announced transaction values in nominal dollars, including assumed debt where that was the headline figure. Curated from SEC filings, FCC orders, and contemporary coverage. Last updated July 2026.',
};
